#ifndef __AUDIO_SETTINGS_H
#define __AUDIO_SETTINGS_H

#define SAMPLE_RATE 46875
#define VOLUME 70
#define AUDIO_BUFFER_SAMPLES 128
#define AUDIO_BUFFER_CHANNELS 2
#define AUDIO_BUFFER_SIZE (AUDIO_BUFFER_SAMPLES * AUDIO_BUFFER_CHANNELS * 2)
#endif
